console.log("question 1 script is running! (SVG with CSS/JS example)");
Promise.all([getHtmlAsync("./question.html")]).then(function ([html]) {
  // populate page with content from question.html
  const questionContent = d3.select(html).selectAll("#inner-container > *");
  questionContent.each(function (d) {
    d3.select("#question-container").node().appendChild(this);
  });

  /******************************
   *  Edit below this line only * 
  /******************************/
  const data = [
    {
      country: "India",
      code_3: "IND",
      code_2: "IN",
      year: 2010,
      plastic_waste: 0.01,
    },
    {
      country: "Mozambique",
      code_3: "MOZ",
      code_2: "MZ",
      year: 2010,
      plastic_waste: 0.015,
    },
    {
      country: "Madagascar",
      code_3: "MDG",
      code_2: "MG",
      year: 2010,
      plastic_waste: 0.016,
    },
    {
      country: "Tanzania",
      code_3: "TZA",
      code_2: "TZ",
      year: 2010,
      plastic_waste: 0.023,
    },
    {
      country: "Brunei",
      code_3: "BRN",
      code_2: "BN",
      year: 2010,
      plastic_waste: 0.026,
    },
    {
      country: "Kenya",
      code_3: "KEN",
      code_2: "KE",
      year: 2010,
      plastic_waste: 0.027,
    },
    {
      country: "Guinea",
      code_3: "GIN",
      code_2: "GN",
      year: 2010,
      plastic_waste: 0.03,
    },
    {
      country: "Bangladesh",
      code_3: "BGD",
      code_2: "BD",
      year: 2010,
      plastic_waste: 0.034,
    },
    {
      country: "Jamaica",
      code_3: "JAM",
      code_2: "JM",
      year: 2010,
      plastic_waste: 0.034,
    },
    {
      country: "Ghana",
      code_3: "GHA",
      code_2: "GH",
      year: 2010,
      plastic_waste: 0.04,
    },
    {
      country: "Sierra Leone",
      code_3: "SLE",
      code_2: "SL",
      year: 2010,
      plastic_waste: 0.041,
    },
    {
      country: "Romania",
      code_3: "ROU",
      code_2: "RO",
      year: 2010,
      plastic_waste: 0.042,
    },
    {
      country: "Benin",
      code_3: "BEN",
      code_2: "BJ",
      year: 2010,
      plastic_waste: 0.043,
    },
    {
      country: "Democratic Republic of Congo",
      code_3: "COD",
      code_2: "CD",
      year: 2010,
      plastic_waste: 0.045,
    },
    {
      country: "Eritrea",
      code_3: "ERI",
      code_2: "ER",
      year: 2010,
      plastic_waste: 0.045,
    },
    {
      country: "Mauritania",
      code_3: "MRT",
      code_2: "MR",
      year: 2010,
      plastic_waste: 0.045,
    },
    {
      country: "Cameroon",
      code_3: "CMR",
      code_2: "CM",
      year: 2010,
      plastic_waste: 0.046,
    },
    {
      country: "Denmark",
      code_3: "DNK",
      code_2: "DK",
      year: 2010,
      plastic_waste: 0.047,
    },
    {
      country: "Gambia",
      code_3: "GMB",
      code_2: "GM",
      year: 2010,
      plastic_waste: 0.048,
    },
    {
      country: "Sweden",
      code_3: "SWE",
      code_2: "SE",
      year: 2010,
      plastic_waste: 0.048,
    },
    {
      country: "Gabon",
      code_3: "GAB",
      code_2: "GA",
      year: 2010,
      plastic_waste: 0.054,
    },
    {
      country: "Guinea-Bissau",
      code_3: "GNB",
      code_2: "GW",
      year: 2010,
      plastic_waste: 0.054,
    },
    {
      country: "North Korea",
      code_3: "PRK",
      code_2: "KP",
      year: 2010,
      plastic_waste: 0.054,
    },
    {
      country: "Somalia",
      code_3: "SOM",
      code_2: "SO",
      year: 2010,
      plastic_waste: 0.054,
    },
    {
      country: "Indonesia",
      code_3: "IDN",
      code_2: "ID",
      year: 2010,
      plastic_waste: 0.057,
    },
    {
      country: "Togo",
      code_3: "TGO",
      code_2: "TG",
      year: 2010,
      plastic_waste: 0.057,
    },
    {
      country: "Angola",
      code_3: "AGO",
      code_2: "AO",
      year: 2010,
      plastic_waste: 0.062,
    },
    {
      country: "Palestine",
      code_3: "PSE",
      code_2: "PS",
      year: 2010,
      plastic_waste: 0.063,
    },
    {
      country: "Cape Verde",
      code_3: "CPV",
      code_2: "CV",
      year: 2010,
      plastic_waste: 0.065,
    },
    {
      country: "Cambodia",
      code_3: "KHM",
      code_2: "KH",
      year: 2010,
      plastic_waste: 0.066,
    },
    {
      country: "Georgia",
      code_3: "GEO",
      code_2: "GE",
      year: 2010,
      plastic_waste: 0.068,
    },
    {
      country: "Albania",
      code_3: "ALB",
      code_2: "AL",
      year: 2010,
      plastic_waste: 0.069,
    },
    {
      country: "Congo",
      code_3: "COG",
      code_2: "CG",
      year: 2010,
      plastic_waste: 0.069,
    },
    {
      country: "Morocco",
      code_3: "MAR",
      code_2: "MA",
      year: 2010,
      plastic_waste: 0.073,
    },
    {
      country: "Myanmar",
      code_3: "MMR",
      code_2: "MM",
      year: 2010,
      plastic_waste: 0.075,
    },
    {
      country: "Philippines",
      code_3: "PHL",
      code_2: "PH",
      year: 2010,
      plastic_waste: 0.075,
    },
    {
      country: "Belgium",
      code_3: "BEL",
      code_2: "BE",
      year: 2010,
      plastic_waste: 0.08,
    },
    {
      country: "Liberia",
      code_3: "LBR",
      code_2: "LR",
      year: 2010,
      plastic_waste: 0.084,
    },
    {
      country: "Oman",
      code_3: "OMN",
      code_2: "OM",
      year: 2010,
      plastic_waste: 0.084,
    },
    {
      country: "Mexico",
      code_3: "MEX",
      code_2: "MX",
      year: 2010,
      plastic_waste: 0.087,
    },
    {
      country: "Cuba",
      code_3: "CUB",
      code_2: "CU",
      year: 2010,
      plastic_waste: 0.089,
    },
    {
      country: "Haiti",
      code_3: "HTI",
      code_2: "HT",
      year: 2010,
      plastic_waste: 0.09,
    },
    {
      country: "Canada",
      code_3: "CAN",
      code_2: "CA",
      year: 2010,
      plastic_waste: 0.093,
    },
    {
      country: "Lebanon",
      code_3: "LBN",
      code_2: "LB",
      year: 2010,
      plastic_waste: 0.094,
    },
    {
      country: "Poland",
      code_3: "POL",
      code_2: "PL",
      year: 2010,
      plastic_waste: 0.097,
    },
    {
      country: "Cote d'Ivoire",
      code_3: "CIV",
      code_2: "CI",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Djibouti",
      code_3: "DJI",
      code_2: "DJ",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Iraq",
      code_3: "IRQ",
      code_2: "IQ",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Kiribati",
      code_3: "KIR",
      code_2: "KI",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Micronesia (country)",
      code_3: "FSM",
      code_2: "FM",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Nigeria",
      code_3: "NGA",
      code_2: "NG",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Norfolk Island",
      code_3: "NFK",
      code_2: "NF",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Pakistan",
      code_3: "PAK",
      code_2: "PK",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Papua New Guinea",
      code_3: "PNG",
      code_2: "PG",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Samoa",
      code_3: "WSM",
      code_2: "WS",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Sao Tome and Principe",
      code_3: "STP",
      code_2: "ST",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Senegal",
      code_3: "SEN",
      code_2: "SN",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Solomon Islands",
      code_3: "SLB",
      code_2: "SB",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Sudan",
      code_3: "SDN",
      code_2: "SD",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Tokelau",
      code_3: "TKL",
      code_2: "TK",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Ukraine",
      code_3: "UKR",
      code_2: "UA",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Vietnam",
      code_3: "VNM",
      code_2: "VN",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Yemen",
      code_3: "YEM",
      code_2: "YE",
      year: 2010,
      plastic_waste: 0.103,
    },
    {
      country: "Australia",
      code_3: "AUS",
      code_2: "AU",
      year: 2010,
      plastic_waste: 0.112,
    },
    {
      country: "Russia",
      code_3: "RUS",
      code_2: "RU",
      year: 2010,
      plastic_waste: 0.112,
    },
    {
      country: "South Korea",
      code_3: "KOR",
      code_2: "KR",
      year: 2010,
      plastic_waste: 0.112,
    },
    {
      country: "Chile",
      code_3: "CHL",
      code_2: "CL",
      year: 2010,
      plastic_waste: 0.119,
    },
    {
      country: "China",
      code_3: "CHN",
      code_2: "CN",
      year: 2010,
      plastic_waste: 0.121,
    },
    {
      country: "Latvia",
      code_3: "LVA",
      code_2: "LV",
      year: 2010,
      plastic_waste: 0.124,
    },
    {
      country: "Bahrain",
      code_3: "BHR",
      code_2: "BH",
      year: 2010,
      plastic_waste: 0.132,
    },
    {
      country: "Lithuania",
      code_3: "LTU",
      code_2: "LT",
      year: 2010,
      plastic_waste: 0.132,
    },
    {
      country: "Italy",
      code_3: "ITA",
      code_2: "IT",
      year: 2010,
      plastic_waste: 0.134,
    },
    {
      country: "Nicaragua",
      code_3: "NIC",
      code_2: "NI",
      year: 2010,
      plastic_waste: 0.143,
    },
    {
      country: "Algeria",
      code_3: "DZA",
      code_2: "DZ",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Bosnia and Herzegovina",
      code_3: "BIH",
      code_2: "BA",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Colombia",
      code_3: "COL",
      code_2: "CO",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Cook Islands",
      code_3: "COK",
      code_2: "CK",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Dominican Republic",
      code_3: "DOM",
      code_2: "DO",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Equatorial Guinea",
      code_3: "GNQ",
      code_2: "GQ",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "French Guiana",
      code_3: "GUF",
      code_2: "GF",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Guadeloupe",
      code_3: "GLP",
      code_2: "GP",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Iran",
      code_3: "IRN",
      code_2: "IR",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Jordan",
      code_3: "JOR",
      code_2: "JO",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Libya",
      code_3: "LBY",
      code_2: "LY",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Montenegro",
      code_3: "MNE",
      code_2: "ME",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Montserrat",
      code_3: "MSR",
      code_2: "MS",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Namibia",
      code_3: "NAM",
      code_2: "NA",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Nauru",
      code_3: "NRU",
      code_2: "NR",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Palau",
      code_3: "PLW",
      code_2: "PW",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Peru",
      code_3: "PER",
      code_2: "PE",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Reunion",
      code_3: "REU",
      code_2: "RE",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Saint Helena",
      code_3: "SHN",
      code_2: "SH",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Thailand",
      code_3: "THA",
      code_2: "TH",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Tunisia",
      code_3: "TUN",
      code_2: "TN",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Tuvalu",
      code_3: "TUV",
      code_2: "TV",
      year: 2010,
      plastic_waste: 0.144,
    },
    {
      country: "Panama",
      code_3: "PAN",
      code_2: "PA",
      year: 2010,
      plastic_waste: 0.145,
    },
    {
      country: "Slovenia",
      code_3: "SVN",
      code_2: "SI",
      year: 2010,
      plastic_waste: 0.145,
    },
    {
      country: "Ecuador",
      code_3: "ECU",
      code_2: "EC",
      year: 2010,
      plastic_waste: 0.147,
    },
    {
      country: "El Salvador",
      code_3: "SLV",
      code_2: "SV",
      year: 2010,
      plastic_waste: 0.147,
    },
    {
      country: "Dominica",
      code_3: "DMA",
      code_2: "DM",
      year: 2010,
      plastic_waste: 0.149,
    },
    {
      country: "Bulgaria",
      code_3: "BGR",
      code_2: "BG",
      year: 2010,
      plastic_waste: 0.154,
    },
    {
      country: "Saudi Arabia",
      code_3: "SAU",
      code_2: "SA",
      year: 2010,
      plastic_waste: 0.156,
    },
    {
      country: "Qatar",
      code_3: "QAT",
      code_2: "QA",
      year: 2010,
      plastic_waste: 0.16,
    },
    {
      country: "Suriname",
      code_3: "SUR",
      code_2: "SR",
      year: 2010,
      plastic_waste: 0.163,
    },
    {
      country: "Brazil",
      code_3: "BRA",
      code_2: "BR",
      year: 2010,
      plastic_waste: 0.165,
    },
    {
      country: "Japan",
      code_3: "JPN",
      code_2: "JP",
      year: 2010,
      plastic_waste: 0.171,
    },
    {
      country: "Belize",
      code_3: "BLZ",
      code_2: "BZ",
      year: 2010,
      plastic_waste: 0.172,
    },
    {
      country: "Estonia",
      code_3: "EST",
      code_2: "EE",
      year: 2010,
      plastic_waste: 0.176,
    },
    {
      country: "Egypt",
      code_3: "EGY",
      code_2: "EG",
      year: 2010,
      plastic_waste: 0.178,
    },
    {
      country: "Syria",
      code_3: "SYR",
      code_2: "SY",
      year: 2010,
      plastic_waste: 0.178,
    },
    {
      country: "Argentina",
      code_3: "ARG",
      code_2: "AR",
      year: 2010,
      plastic_waste: 0.183,
    },
    {
      country: "Fiji",
      code_3: "FJI",
      code_2: "FJ",
      year: 2010,
      plastic_waste: 0.189,
    },
    {
      country: "Honduras",
      code_3: "HND",
      code_2: "HN",
      year: 2010,
      plastic_waste: 0.189,
    },
    {
      country: "France",
      code_3: "FRA",
      code_2: "FR",
      year: 2010,
      plastic_waste: 0.192,
    },
    {
      country: "Marshall Islands",
      code_3: "MHL",
      code_2: "MH",
      year: 2010,
      plastic_waste: 0.192,
    },
    {
      country: "Singapore",
      code_3: "SGP",
      code_2: "SG",
      year: 2010,
      plastic_waste: 0.194,
    },
    {
      country: "Malaysia",
      code_3: "MYS",
      code_2: "MY",
      year: 2010,
      plastic_waste: 0.198,
    },
    {
      country: "United Arab Emirates",
      code_3: "ARE",
      code_2: "AE",
      year: 2010,
      plastic_waste: 0.199,
    },
    {
      country: "Greece",
      code_3: "GRC",
      code_2: "GR",
      year: 2010,
      plastic_waste: 0.2,
    },
    {
      country: "Comoros",
      code_3: "COM",
      code_2: "KM",
      year: 2010,
      plastic_waste: 0.201,
    },
    {
      country: "Turkey",
      code_3: "TUR",
      code_2: "TR",
      year: 2010,
      plastic_waste: 0.212,
    },
    {
      country: "Malta",
      code_3: "MLT",
      code_2: "MT",
      year: 2010,
      plastic_waste: 0.214,
    },
    {
      country: "United Kingdom",
      code_3: "GBR",
      code_2: "GB",
      year: 2010,
      plastic_waste: 0.215,
    },
    {
      country: "Saint Vincent and the Grenadines",
      code_3: "VCT",
      code_2: "VC",
      year: 2010,
      plastic_waste: 0.221,
    },
    {
      country: "Tonga",
      code_3: "TON",
      code_2: "TO",
      year: 2010,
      plastic_waste: 0.223,
    },
    {
      country: "Mauritius",
      code_3: "MUS",
      code_2: "MU",
      year: 2010,
      plastic_waste: 0.23,
    },
    {
      country: "Finland",
      code_3: "FIN",
      code_2: "FI",
      year: 2010,
      plastic_waste: 0.234,
    },
    {
      country: "South Africa",
      code_3: "ZAF",
      code_2: "ZA",
      year: 2010,
      plastic_waste: 0.24,
    },
    {
      country: "Cyprus",
      code_3: "CYP",
      code_2: "CY",
      year: 2010,
      plastic_waste: 0.248,
    },
    {
      country: "Anguilla",
      code_3: "AIA",
      code_2: "AI",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Aruba",
      code_3: "ABW",
      code_2: "AW",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Bermuda",
      code_3: "BMU",
      code_2: "BM",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "British Virgin Islands",
      code_3: "VGB",
      code_2: "VG",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Cayman Islands",
      code_3: "CYM",
      code_2: "KY",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Christmas Island",
      code_3: "CXR",
      code_2: "CX",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Cocos Islands",
      code_3: "CCK",
      code_2: "CC",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Croatia",
      code_3: "HRV",
      code_2: "HR",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Faeroe Islands",
      code_3: "FRO",
      code_2: "FO",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Falkland Islands",
      code_3: "FLK",
      code_2: "FK",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "French Polynesia",
      code_3: "PYF",
      code_2: "PF",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Gibraltar",
      code_3: "GIB",
      code_2: "GI",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Greenland",
      code_3: "GRL",
      code_2: "GL",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Guam",
      code_3: "GUM",
      code_2: "GU",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Guernsey",
      code_3: "GGY",
      code_2: "GG",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Martinique",
      code_3: "MTQ",
      code_2: "MQ",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Monaco",
      code_3: "MCO",
      code_2: "MC",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Netherlands Antilles",
      code_3: "ANT",
      code_2: "AN",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "New Caledonia",
      code_3: "NCL",
      code_2: "NC",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Niue",
      code_3: "NIU",
      code_2: "NU",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Northern Mariana Islands",
      code_3: "MNP",
      code_2: "MP",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Puerto Rico",
      code_3: "PRI",
      code_2: "PR",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Saint Pierre and Miquelon",
      code_3: "SPM",
      code_2: "PM",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Taiwan",
      code_3: "TWN",
      code_2: "TW",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Turks and Caicos Islands",
      code_3: "TCA",
      code_2: "TC",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Uruguay",
      code_3: "URY",
      code_2: "UY",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Venezuela",
      code_3: "VEN",
      code_2: "VE",
      year: 2010,
      plastic_waste: 0.252,
    },
    {
      country: "Costa Rica",
      code_3: "CRI",
      code_2: "CR",
      year: 2010,
      plastic_waste: 0.258,
    },
    {
      country: "Portugal",
      code_3: "PRT",
      code_2: "PT",
      year: 2010,
      plastic_waste: 0.265,
    },
    {
      country: "Spain",
      code_3: "ESP",
      code_2: "ES",
      year: 2010,
      plastic_waste: 0.277,
    },
    {
      country: "Guatemala",
      code_3: "GTM",
      code_2: "GT",
      year: 2010,
      plastic_waste: 0.28,
    },
    {
      country: "Norway",
      code_3: "NOR",
      code_2: "NO",
      year: 2010,
      plastic_waste: 0.28,
    },
    {
      country: "Iceland",
      code_3: "ISL",
      code_2: "IS",
      year: 2010,
      plastic_waste: 0.281,
    },
    {
      country: "Trinidad and Tobago",
      code_3: "TTO",
      code_2: "TT",
      year: 2010,
      plastic_waste: 0.29,
    },
    {
      country: "Vanuatu",
      code_3: "VUT",
      code_2: "VU",
      year: 2010,
      plastic_waste: 0.295,
    },
    {
      country: "Israel",
      code_3: "ISR",
      code_2: "IL",
      year: 2010,
      plastic_waste: 0.297,
    },
    {
      country: "Maldives",
      code_3: "MDV",
      code_2: "MV",
      year: 2010,
      plastic_waste: 0.322,
    },
    {
      country: "Grenada",
      code_3: "GRD",
      code_2: "GD",
      year: 2010,
      plastic_waste: 0.325,
    },
    {
      country: "New Zealand",
      code_3: "NZL",
      code_2: "NZ",
      year: 2010,
      plastic_waste: 0.331,
    },
    {
      country: "United States",
      code_3: "USA",
      code_2: "US",
      year: 2010,
      plastic_waste: 0.335,
    },
    {
      country: "Sri Lanka",
      code_3: "LKA",
      code_2: "LK",
      year: 2010,
      plastic_waste: 0.357,
    },
    {
      country: "Seychelles",
      code_3: "SYC",
      code_2: "SC",
      year: 2010,
      plastic_waste: 0.358,
    },
    {
      country: "Macao",
      code_3: "MAC",
      code_2: "MO",
      year: 2010,
      plastic_waste: 0.368,
    },
    {
      country: "Bahamas",
      code_3: "BHS",
      code_2: "BS",
      year: 2010,
      plastic_waste: 0.39,
    },
    {
      country: "Hong Kong",
      code_3: "HKG",
      code_2: "HK",
      year: 2010,
      plastic_waste: 0.398,
    },
    {
      country: "Netherlands",
      code_3: "NLD",
      code_2: "NL",
      year: 2010,
      plastic_waste: 0.424,
    },
    {
      country: "Ireland",
      code_3: "IRL",
      code_2: "IE",
      year: 2010,
      plastic_waste: 0.43,
    },
    {
      country: "Germany",
      code_3: "DEU",
      code_2: "DE",
      year: 2010,
      plastic_waste: 0.485,
    },
    {
      country: "Saint Lucia",
      code_3: "LCA",
      code_2: "LC",
      year: 2010,
      plastic_waste: 0.522,
    },
    {
      country: "Barbados",
      code_3: "BRB",
      code_2: "BB",
      year: 2010,
      plastic_waste: 0.57,
    },
    {
      country: "Guyana",
      code_3: "GUY",
      code_2: "GY",
      year: 2010,
      plastic_waste: 0.586,
    },
    {
      country: "Saint Kitts and Nevis",
      code_3: "KNA",
      code_2: "KN",
      year: 2010,
      plastic_waste: 0.654,
    },
    {
      country: "Antigua and Barbuda",
      code_3: "ATG",
      code_2: "AG",
      year: 2010,
      plastic_waste: 0.66,
    },
    {
      country: "Kuwait",
      code_3: "KWT",
      code_2: "KW",
      year: 2010,
      plastic_waste: 0.686,
    },
  ];

  const countryNameEl = document.querySelector(
    "#plastic-map-container .info p"
  );

  const highlightGroup = (groups) => {
    groups.forEach((country) => {
      const path = document.querySelector(
        `#plastic-map-container #${country.code_2.toLowerCase()}`
      );
      const kgClass = Math.min(Math.ceil(country.plastic_waste * 10), 5);
      path?.classList.toggle(`active-${kgClass}`);
    });
  };

  highlightGroup(data);

  const paths = document.querySelectorAll("#plastic-map-container svg > g > *");
  // console.log(paths);
  const showCountry = (e) => {
    const countryObj = data.find(
      (x) => x.code_2.toLowerCase() === e.currentTarget.id
    );
    countryNameEl.innerHTML =
      countryObj?.country +
      "<br> " +
      countryObj?.plastic_waste +
      "<span> kg per capita</span>";
  };

  const hideCountry = (e) => {
    countryNameEl.innerHTML = "";
  };

  paths.forEach((p) => {
    p.addEventListener("mouseover", showCountry);
    p.addEventListener("touchstart", showCountry);

    p.addEventListener("mouseout", hideCountry);
    p.addEventListener("touchend", hideCountry);
  });

  // Use d3js for interactions ...
});
